version: '3.8'

services:
  minitrue:
    build: .
    container_name: minitrue
    ports:
      - "8303:8501"
    volumes:
      - .:/app
      - /mnt/8tb/Audio:/music  # Mount the ROOT for relative symlink resolution
    command: streamlit run app.py --server.address=0.0.0.0 --server.runOnSave=true
    restart: unless-stopped